// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTPVAWk3JFv_XWkbcCcQaVsAC40QrPI_c',
    appId: '1:898542021130:web:960772933fb6783f294df3',
    messagingSenderId: '898542021130',
    projectId: 'd2c-sale',
    authDomain: 'd2c-sale.firebaseapp.com',
    storageBucket: 'd2c-sale.firebasestorage.app',
    measurementId: 'G-T16YBRW2HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7LIRAeaAQF6lSeB-xbuVi8TpAe1t2udk',
    appId: '1:898542021130:android:7a0fb66c83d6da41294df3',
    messagingSenderId: '898542021130',
    projectId: 'd2c-sale',
    storageBucket: 'd2c-sale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8hONQIGgiihmklteot7x_8m0qkY4h5Bg',
    appId: '1:898542021130:ios:7e3c621f6623f7c2294df3',
    messagingSenderId: '898542021130',
    projectId: 'd2c-sale',
    storageBucket: 'd2c-sale.firebasestorage.app',
    iosBundleId: 'com.deals.d2c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8hONQIGgiihmklteot7x_8m0qkY4h5Bg',
    appId: '1:898542021130:ios:7e3c621f6623f7c2294df3',
    messagingSenderId: '898542021130',
    projectId: 'd2c-sale',
    storageBucket: 'd2c-sale.firebasestorage.app',
    iosBundleId: 'com.deals.d2c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTPVAWk3JFv_XWkbcCcQaVsAC40QrPI_c',
    appId: '1:898542021130:web:0c5eae879e553eba294df3',
    messagingSenderId: '898542021130',
    projectId: 'd2c-sale',
    authDomain: 'd2c-sale.firebaseapp.com',
    storageBucket: 'd2c-sale.firebasestorage.app',
    measurementId: 'G-E321D91523',
  );
}
