name: D2Cdeals
description: "D2Cdeals: All in one Offers and Deals App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1 
  share_plus: ^10.1.3
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  firebase_analytics: ^11.4.0
  shared_preferences: ^2.3.5
  cloud_firestore: ^5.6.1
  onesignal_flutter: ^5.2.9
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
